# Example configuration for the refactored pipeline

bbox: [-64.651794, -15.010122, -64.572144, -14.952414]
out_dir: example_output

step1:
  enabled: true
  fetch_cop_tiles:
    enabled: true
    source_dirs: []
  fetch_gedi_points:
    enabled: true
    time_start: '2017-01-01'
    time_end: '2025-01-01'
    source_dirs: []
  visualize: true

sentinel:
  enabled: false
  time_start: '2024-01-01'
  time_end: '2024-12-31'
  max_cloud: 20
  visualize: true
  dpi: 150
  source_dirs: []

srtm:
  enabled: false
  visualize: true
  source_dirs: []

step2:
  enabled: true
  resolution: 0.0002695
  visualize: true

step3:
  enabled: true
  visualize: true

step4:
  enabled: true
  sigma: .002
  amp_thresh: 25
  size_thresh_m: 1
  visualize: true
  save_json: true
  debug: true

step5:
  enabled: true
  include_data_vis: true
  include_full_sentinel: true

step6:
  enabled: true
  bare_earth_file: bare_earth.obj
  dem_file: dem_crop.obj
  scale: 0.01

step7:
  enabled: true
  bare_earth_file: bare_earth.xyz
  dem_file: dem_crop.xyz
  scale: 0.01
