# Example configuration for the refactored pipeline

bbox:
  - [-64.651794, -15.010122, -64.572144, -14.952414]
  - [-65.651794, -16.010122, -63.572144, -13.952414]
out_dir: example_output

fetch_data:
  enabled: true
  fetch_cop_tiles:
    enabled: true
    source_dirs: []
  fetch_gedi_points:
    enabled: true
    time_start: '2017-01-01'
    time_end: '2025-01-01'
    source_dirs: []
    force_download: false
  visualize: true

sentinel:
  enabled: true
  high_stress:
    time_start: '2024-01-01'
    time_end: '2024-12-31'
  low_stress:
    time_start: '2022-05-01'
    time_end: '2022-06-30'
  max_cloud: 5
  visualize: true
  resize_vis: false
  save_full: false
  dpi: 150
  source_dirs: []

srtm:
  enabled: true
  visualize: true
  source_dirs: []

aw3d:
  enabled: true
  visualize: true
  source_dirs: []

bare_earth:
  enabled: true
  resolution: 0.0002695
  visualize: true

residual_relief:
  enabled: true
  visualize: true
  # Optional list of DEMs to subtract from the GEDI bare-earth surface.
  # Specify by name: "cop", "srtm", "aw3d". Multiple entries will be averaged
  # before subtraction.
  dems: ['aw3d']

detect_anomalies:
  enabled: true
  sigma: .002
  amp_thresh: 25
  size_thresh_m: 1
  visualize: true
  save_json: true
  debug: true

interactive_map:
  enabled: true
  include_data_vis: true
  include_full_sentinel: false
  include_full_srtm: false
  include_full_aw3d: false

export_obj:
  enabled: true
  bare_earth_file: bare_earth.obj
  dem_file: dem_crop.obj
  scale: 0.01

export_xyz:
  enabled: true
  bare_earth_file: bare_earth.xyz
  dem_file: dem_crop.xyz
  scale: 0.01

chatgpt:
  enabled: false
  model: o3
  images:
    - sample
  prompt: "Identify any man-made features in these images."
  log_level: info
